### ISSUE TITLE
Does not work with 6000.3

### ISSUE THREAD

**Issue by Fire-Aalt** [Fribur/TextMeshDOTS#43]
As the official release of 6000.3 will be in less than a week, it would be very helpful to add support for it. Right now, most of the compilation errors refer to changed internal API. I wish I could use this library as using TMP for damage numbers results in terrible perforamance due to allocations and GameObject overhead

**Comment by Fribur** [comment]
The AtlasArray branch works with 6.3

**Comment by grapefruitlips** [comment]
Yeah, not working in 6000.3.0b10, 
FontEngine.GetSystemFontReferences() in TextCoreExtensions is not working

**Comment by Fire-Aalt** [comment]
I see that in the branch AtlasArrays branch, there are a few issues. I understand that the branch is in active development, so here is a list of issues I encountered. Unity 6000.3.0f1, URP

Doesn't compile because of a useless [SerializeReference]:
<img width="2632" height="291" alt="Image" src="https://github.com/user-attachments/assets/5347128e-0b04-4570-8cea-b699c81a6ca2" />

Text looks broken, seems like a bug in the text rendering (this is a Roboto variable font loaded as an embedded font): 
<img width="1522" height="249" alt="Image" src="https://github.com/user-attachments/assets/8bcc8862-fa11-4de4-9f1b-84bcf58de008" />

The text is only shown in the open subscene. Closing the subscene results in the warning:
<img width="1207" height="53" alt="Image" src="https://github.com/user-attachments/assets/aa9dcdb2-d85a-4c2f-8a1e-a0f4a3976adf" />

Here is the authoring gameobject:
<img width="1200" height="1600" alt="Image" src="https://github.com/user-attachments/assets/7e676a9f-743a-4d41-b38f-4b08753e4ad9" />

**Comment by Fribur** [comment]
Thanks for reporting those issues. Should be resolved now, except for the buggy rendering which is not easy to fix as explained in https://discussions.unity.com/t/0-9-0-textmeshdots-world-space-dots-native-text/946438/20 (need a new renderer). In the meantime, I would suggest to switch to a font where the glyphs are not defined via overlapping outlines (e.g. static OpenType fonts (otf) are guarantied to not have them)
